In [1]:
import tensorflow as tf
import tensorflow.keras as keras
from itertools import groupby
import numpy as np

In [23]:
def faiter(file):
    """
    funkcja zwraca generator. kazdy loop generatora 
    zawiera header oraz połączoną z poj. linii sekwencję.
    sekwencja grupowana jest do headera za pomocą groupby().
    """
    fh = open(file)
    for group, group_items_iter in groupby(fh, lambda line: line[0] == ">"):
        header_seq_joined = "".join(group_items_iter)
        yield header_seq_joined

def single_sequence(faiter_output):
    """
    funkcja zwraca pojedyncza sekwencję
    wraz z jej headerem w oddzielnych zmiennych
    """
    header = faiter_output.__next__().replace('\n', '')
    sequence = faiter_output.__next__().replace('\n', '')
    return (header, sequence)

def check_no_of_sequences(file):
    sequences_count = 0
    f = open(file)

    for line in f:
        if line.startswith(">"):
            sequences_count += 1
    return sequences_count

In [ ]:
def split_seq(sequence, header):
    

In [90]:
def one_hot_in_buckets(sequence):
    nucleotides = {
        'A': [0,0,0,1],
        'G': [0,0,1,0],
        'C': [0,1,0,0],
        'T': [1,0,0,0]
        }
    one_hot_sequence = []       # Never append to numpy arrays in a loop: it is the one operation that NumPy is very bad at compared with basic Python. This is because you are making a full copy of the data each append, which will cost you quadratic time. 
    seq_len = 0
    for nucleotide in sequence:
        #if nucleotide not in nucleotides.items():
        #    break
        for nuc_name, nuc_value in nucleotides.items():
            if nucleotide == nuc_name:
                one_hot_sequence.append(nuc_value)
                seq_len += 1
                if seq_len == 300:
                    one_hot_sequence = np.asarray(one_hot_sequence)
                    yield one_hot_sequence
                    seq_len = 0
                    one_hot_sequence = []

if __name__ == "__main__":
    examined_file = 'lncrna_rep/gencode.v33.lncRNA_transcripts.fa'
    faiter_output = faiter(examined_file)
    no_of_sequences = check_no_of_sequences(examined_file)

    seq_array = []
    count = 0
    while count < 50000:        
        header, sequence = single_sequence(faiter_output)

        one_hot_sequence = one_hot_in_buckets(sequence)
        #seq_array = np.append(seq_array, one_hot_sequence, axis=0)
        
        try:
            while True:
                seq_array.append(one_hot_sequence.__next__())
                count += 1
        except StopIteration:
            pass
        
        
        

        #if len(sequence) < 3001:
        #    seq_array.append(one_hot_sequence)
        count += 1
    
    #padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(seq_array, padding='post', value=2)
    #padded_inputs = np.asarray(padded_inputs)
    seq_array = np.asarray(seq_array)

    
    #print(seq_array)
    print(seq_array.shape)
    
    #print(padded_inputs.shape)
    #print(padded_inputs)
    np.save("lncrna_rep/NCT_300nt.npy", seq_array)
    


(39244, 300, 4)


In [89]:
import sys
np.set_printoptions(threshold=sys.maxsize)

print(seq_array[1])

  #      'A': [0,0,0,1],
   #     'G': [0,0,1,0],
    #    'C': [0,1,0,0],
     #   'T': [1,0,0,0]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]

In [5]:
# .npy files generated, now load files and combine them (after restarting kernel)

PCT = np.load('lncrna_rep/PCT_300nt.npy')
NCT = np.load('lncrna_rep/NCT_300nt.npy')


In [6]:
PCT_train = PCT[:34000]
PCT_test = PCT[34000:]

NCT_train = NCT[:34000]
NCT_test = NCT[34000:]
PCT_train.shape

(34000, 300, 4)

In [7]:
NCT_test.shape

(5244, 300, 4)

In [8]:
x_train = np.vstack([PCT_train, NCT_train])
x_train.shape

x_test = np.vstack([PCT_test, NCT_test])
x_train.shape

(68000, 300, 4)

In [9]:
y_train_1 = np.ones(34000)
y_train_2 = np.zeros(34000)
y_train = np.hstack([y_train_1, y_train_2])
y_train = keras.utils.to_categorical(y_train, 2)
y_train.shape

y_test_1 = np.ones(9877) # 1 = PC, 0 = NC (?)
y_test_2 = np.zeros(5244)
y_test = np.hstack([y_test_1, y_test_2])
y_test = keras.utils.to_categorical(y_test, 2)
y_test.shape

(15121, 2)

In [2]:
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Dropout, Flatten, Reshape, GlobalAveragePooling1D, Activation
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Conv1D, MaxPooling1D
#from tensorflow.keras.utils import np_utils

In [23]:
model_m = Sequential()

model_m.add(tf.keras.layers.Masking(mask_value=0.,input_shape=(3000, 4)))


model_m.add(Conv1D(50, 15, activation='relu', ))

model_m.add(Conv1D(50, 15, activation='relu'))
model_m.add(MaxPooling1D(3))
model_m.add(Conv1D(80, 15, activation='relu'))
model_m.add(Conv1D(80, 15, activation='relu'))
model_m.add(GlobalAveragePooling1D())
model_m.add(Dropout(0.5))
model_m.add(Dense(2, activation='softmax'))
print(model_m.summary())

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
masking_2 (Masking)          (None, 3000, 4)           0         
_________________________________________________________________
conv1d_20 (Conv1D)           (None, 2986, 50)          3050      
_________________________________________________________________
conv1d_21 (Conv1D)           (None, 2972, 50)          37550     
_________________________________________________________________
max_pooling1d_5 (MaxPooling1 (None, 990, 50)           0         
_________________________________________________________________
conv1d_22 (Conv1D)           (None, 976, 80)           60080     
_________________________________________________________________
conv1d_23 (Conv1D)           (None, 962, 80)           96080     
_________________________________________________________________
global_average_pooling1d_5 ( (None, 80)               

In [24]:
#callbacks_list = [
#    keras.callbacks.ModelCheckpoint(
 #       filepath='best_model.{epoch:02d}-{val_loss:.2f}.h5',
  #      monitor='val_loss', save_best_only=True),
   # )
#]

callbacks_list = [keras.callbacks.EarlyStopping(monitor='acc', patience=1)]

model_m.compile(loss='categorical_crossentropy',
                optimizer='adam', metrics=['accuracy'])

BATCH_SIZE = 400
EPOCHS = 10

history = model_m.fit(x_train,
                      y_train,
                      batch_size=BATCH_SIZE,
                      epochs=EPOCHS,
                      callbacks=callbacks_list)
                      

Train on 50000 samples
Epoch 1/10
50000/50000 [==============================] - 177s 4ms/sample - loss: 0.6343 - acc: 0.6330
Epoch 2/10
50000/50000 [==============================] - 168s 3ms/sample - loss: 0.5070 - acc: 0.7527
Epoch 3/10
50000/50000 [==============================] - 168s 3ms/sample - loss: 0.4498 - acc: 0.7953
Epoch 4/10
50000/50000 [==============================] - 168s 3ms/sample - loss: 0.4330 - acc: 0.8035
Epoch 5/10
50000/50000 [==============================] - 168s 3ms/sample - loss: 0.4149 - acc: 0.8187
Epoch 6/10
50000/50000 [==============================] - 168s 3ms/sample - loss: 0.3882 - acc: 0.8340
Epoch 7/10
50000/50000 [==============================] - 168s 3ms/sample - loss: 0.3712 - acc: 0.8434
Epoch 8/10
50000/50000 [==============================] - 168s 3ms/sample - loss: 0.3445 - acc: 0.8594
Epoch 9/10
50000/50000 [==============================] - 168s 3ms/sample - loss: 0.3220 - acc: 0.8689
Epoch 10/10
50000/50000 [=========================

In [8]:
model_m.save('lncrna_rep/my_model.h5')

NameError: name 'model_m' is not defined

In [12]:
# load model and continue to train:
loaded_model = load_model("lncrna_rep/my_model.h5")

In [13]:
callbacks_list = [keras.callbacks.EarlyStopping(monitor='acc', patience=1)]

loaded_model.fit(x_train, y_train, epochs=20, batch_size=400, callbacks=callbacks_list)

Train on 50000 samples
Epoch 1/20
50000/50000 [==============================] - 187s 4ms/sample - loss: 0.2992 - acc: 0.8810
Epoch 2/20
50000/50000 [==============================] - 169s 3ms/sample - loss: 0.2819 - acc: 0.8889
Epoch 3/20
50000/50000 [==============================] - 169s 3ms/sample - loss: 0.2591 - acc: 0.8991
Epoch 4/20
50000/50000 [==============================] - 169s 3ms/sample - loss: 0.2452 - acc: 0.9054
Epoch 5/20
50000/50000 [==============================] - 168s 3ms/sample - loss: 0.2342 - acc: 0.9110
Epoch 6/20
50000/50000 [==============================] - 168s 3ms/sample - loss: 0.2411 - acc: 0.9070


In [14]:
loaded_model.save('lncrna_rep/my_model2.h5')

In [100]:
model_m = Sequential()

model_m.add(tf.keras.layers.Masking(mask_value=2, input_shape=(3000, 4)))
model_m.add(Conv1D(64, 21, activation='relu'))
model_m.add(MaxPooling1D(2))
model_m.add(Dropout(0.5))
model_m.add(Flatten())
model_m.add(Dense(64, activation='relu'))
#model_m.add(Dense(256, activation='relu'))
model_m.add(Dense(2))
model_m.add(Activation('softmax'))
print(model_m.summary())

Model: "sequential_52"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
masking_52 (Masking)         (None, 3000, 4)           0         
_________________________________________________________________
conv1d_90 (Conv1D)           (None, 2980, 64)          5440      
_________________________________________________________________
max_pooling1d_90 (MaxPooling (None, 1490, 64)          0         
_________________________________________________________________
dropout_69 (Dropout)         (None, 1490, 64)          0         
_________________________________________________________________
flatten_40 (Flatten)         (None, 95360)             0         
_________________________________________________________________
dense_58 (Dense)             (None, 64)                6103104   
_________________________________________________________________
dense_59 (Dense)             (None, 2)               

In [101]:
callbacks_list = [keras.callbacks.EarlyStopping(monitor='acc', patience=1)]

model_m.compile(loss='categorical_crossentropy',
                optimizer='adam', metrics=['accuracy'])

BATCH_SIZE = 16
EPOCHS = 50

history = model_m.fit(x_train,
                      y_train,
                      batch_size=BATCH_SIZE,
                      epochs=EPOCHS,
                      callbacks=callbacks_list,
                     )
                      # validation_data=(x_test, y_test)

Train on 44000 samples
Epoch 1/50


ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[16,1490,64] and type bool on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node dropout_69/cond/dropout/GreaterEqual}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[metrics_64/acc/Identity/_1715]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[16,1490,64] and type bool on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node dropout_69/cond/dropout/GreaterEqual}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

In [19]:
# 300bp data

model_m = Sequential()


model_m.add(Conv1D(50, 15, activation='relu', input_shape=(300, 4)))

model_m.add(Conv1D(50, 15, activation='relu'))
model_m.add(MaxPooling1D(3))
model_m.add(Conv1D(80, 15, activation='relu'))
model_m.add(Conv1D(80, 15, activation='relu'))
model_m.add(GlobalAveragePooling1D())
model_m.add(Dropout(0.5))
model_m.add(Dense(2, activation='softmax'))
print(model_m.summary())

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_4 (Conv1D)            (None, 286, 50)           3050      
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 272, 50)           37550     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 90, 50)            0         
_________________________________________________________________
conv1d_6 (Conv1D)            (None, 76, 80)            60080     
_________________________________________________________________
conv1d_7 (Conv1D)            (None, 62, 80)            96080     
_________________________________________________________________
global_average_pooling1d_1 ( (None, 80)                0         
_______________________________________

In [20]:
callbacks_list = [keras.callbacks.EarlyStopping(monitor='acc', patience=1)]

model_m.compile(loss='categorical_crossentropy',
                optimizer='adam', metrics=['accuracy'])

BATCH_SIZE = 400
EPOCHS = 50

history = model_m.fit(x_train,
                      y_train,
                      batch_size=BATCH_SIZE,
                      epochs=EPOCHS,
                      callbacks=callbacks_list,
                     )
                      # validation_data=(x_test, y_test)

Train on 68000 samples
Epoch 1/50
68000/68000 [==============================] - 105s 2ms/sample - loss: 0.6413 - acc: 0.6213
Epoch 2/50
68000/68000 [==============================] - 86s 1ms/sample - loss: 0.5955 - acc: 0.6659
Epoch 3/50
68000/68000 [==============================] - 86s 1ms/sample - loss: 0.5634 - acc: 0.6951
Epoch 4/50
68000/68000 [==============================] - 86s 1ms/sample - loss: 0.5240 - acc: 0.7285
Epoch 5/50
68000/68000 [==============================] - 87s 1ms/sample - loss: 0.4819 - acc: 0.7602
Epoch 6/50
68000/68000 [==============================] - 86s 1ms/sample - loss: 0.4465 - acc: 0.7834
Epoch 7/50
68000/68000 [==============================] - 87s 1ms/sample - loss: 0.4031 - acc: 0.8105
Epoch 8/50
68000/68000 [==============================] - 87s 1ms/sample - loss: 0.3744 - acc: 0.8266
Epoch 9/50
68000/68000 [==============================] - 87s 1ms/sample - loss: 0.3360 - acc: 0.8494
Epoch 10/50
68000/68000 [==============================] -

In [21]:
model_m.save('lncrna_rep/my_model_300bp_1.h5')

In [4]:
model_m = load_model("lncrna_rep/my_model_300bp_1.h5")

In [10]:
model_m.evaluate(x_test, y_test)

15121/15121 [==============================] - 33s 2ms/sample - loss: 1.7773 - acc: 0.6715


[1.7773298041367318, 0.6714503]